server:
  port: 8763
spring:
  profiles:
    include: kafka
    active: kafka
  datasource:
    name: mysql
    url: jdbc:mysql://10.10.203.106:8066/dev_db?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: dev_mycat
    password: dev_mycat
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 35
    initialSize: 2
    maxWait: 30000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: false
    maxOpenPreparedStatements: -1
    ogAbandoned: true 
    removeAbandoned: true
    removeAbandonedTimeout: 180
mybatis:
  basepackage: com.jieshun.jsis.message.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: classpath*:mapper/**/*.xml
 
logging:
  config: target/classes/config/log4j2-spring.xml

